<a href="https://colab.research.google.com/github/anoopjakob/AI_Lab_7_Naive_Bayes/blob/main/A_7_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.In this lab, you are going to implement Naive Bayes algorithm using the following
”Zoo” data set.

The Zoo data set taken from UCI data repository contains data items that describe
animals according to certain attributes that categorize them under 7 different classes.

This data set consists of 101 animals from a zoo. There are 17 variables with various
traits to describe the animals. The 7 Class Types are: Mammal, Bird, Reptile, Fish,
Amphibian, Bug and Invertebrate.
Implement Naive Bayes algorithm to predict the class of the animals, based upon the
variables.

For building the model, split the data set into train set and test set (80:20). Use the
train set to build the model and the report the accuracy of your model using the test
data.

The data set and information about the same is uploaded in Google classroom. You
can download from there.

In [ ]:
# Importing the necessary libraries

import numpy as np
import pandas as pd



In [ ]:
# using panda to load the csv file into a Dataframe
zooDf =  pd.read_csv('/content/drive/MyDrive/Classroom/M1 AI - Artificial Intelligence Lab - 2020-21 Semester 1 M.Tech – AI (2020 M.tech admission)/Anoop Jacob - zoo_data_set', 
                     names=['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'ariborne', 'aquatic', 'predator', 'toothed', 'backbone', 'breathes',
                    'venomous', 'fins', 'legs', 'tail', 'domestic', 'catsize', 'type'])


zooDf.head()


animal_name  hair  feathers  eggs  milk  ...  legs  tail  domestic  catsize  type
0    aardvark     1         0     0     1  ...     4     0         0        1     1
1    antelope     1         0     0     1  ...     4     1         0        1     1
2        bass     0         0     1     0  ...     0     1         0        0     4
3        bear     1         0     0     1  ...     4     0         0        1     1
4        boar     1         0     0     1  ...     4     1         0        1     1

[5 rows x 18 columns]

In [ ]:
# converting the dataframe into list for using in scikit learn

zooDataset = zooDf.values.tolist()
len(zooDataset[0])

18

In [ ]:
# ONLY RUN ONCE 

# since we dont need the name column we are popping the first column out from each rows

for row in zooDataset:
    name = row.pop(0) 

# we are going to split the data into feature dataset(16 columns) and target datasets(column: type)

target_dataset =[]
for row in zooDataset:
  target = row.pop(-1) # pop the last column from each row
  target_dataset.append(target) # save the value popped into target_dataset list.

In [ ]:
# using scikit learn's naive bayes model to predict the type/class

from sklearn import datasets
from sklearn import  metrics
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB, CategoricalNB
from sklearn.model_selection import train_test_split

In [ ]:
# code to split the dataset into 80:20 ratio for training and testing using sklearn

zoo_train_dataset, zoo_test_dataset, train_target, test_target = train_test_split(zooDataset, target_dataset, test_size = 0.2, random_state = 11)

print('zoo_train_dataset shape : ({},{})'.format(len(zoo_train_dataset), len(zoo_train_dataset[0])))
print('zoo_test_dataset shape : ({},{})'.format(len(zoo_test_dataset), len(zoo_test_dataset[0])))
print('train_target shape : ({},{})'.format(len(train_target), 1))
print('test_target shape : ({},{})'.format(len(test_target), 1))

zoo_train_dataset shape : (80,16)
zoo_test_dataset shape : (21,16)
train_target shape : (80,1)
test_target shape : (21,1)


In [ ]:
# using multinomial naive bayes model for multivariate classification problem

# zoo_train_dataset and train_target are used for training/ fitting the model
model = MultinomialNB() 
                        

model.fit(zoo_train_dataset, train_target) # fitting the model/ training the model

# test_target and zoo_test_target are used for prediction
expected = test_target

predicted = model.predict(zoo_test_dataset) # model predictoin is done here

def Accuracy(y, yhat):
  count =0
  for i in range(len(y)):
    if yhat[i] == y[i]:
      count+=1
  return count/len(y)*100

accuracy = Accuracy(expected, predicted)

print('The accuracy of the prediction is : ', accuracy)

The accuracy of the prediction is :  95.23809523809523


In [ ]:
model

# "alpha" is set to 1 .. (the number of counts we add to each feature to make it a non zero number)
# also known as smoothing parameter

# "fit prior": Whether to learn class prior probabilities or not. If false, a uniform prior will be used.


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
import warnings
warnings.filterwarnings('ignore')  

# some metrics to assess our model
print('Classification Report')
print(metrics.classification_report(expected, predicted))

print('\n \n Convolution Matrix \n')
print(metrics.confusion_matrix(expected, predicted))

Classification Report
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       0.86      1.00      0.92         6
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         3
           7       0.00      0.00      0.00         1

    accuracy                           0.95        21
   macro avg       0.81      0.83      0.82        21
weighted avg       0.91      0.95      0.93        21


 
 Convolution Matrix 

[[9 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 3 0]
 [0 1 0 0 0 0]]
